version: '3.4'

services:
  # Infrastructure
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./deploy/sql/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql

  otel.collector:
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
    volumes:
      - ./deploy/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  # Application
  bz.fott.administration.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Administration=Server=fott-postgres;Port=5432;Database=fott_administration;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://fott-otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro