receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
    #timeout: 1s

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: fott-jaeger:14250
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]